### ISSUE TITLE
Increase docker data volume pool size

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE#126]
Jenkins is failing to provision build containers with the following error : 

```
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='x86_64 u1404', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@114ff06b, remoteFsMapping='/var/lib/jenkins', remoteFs='/home/jenkins', instanceCap=25, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@6bdc7aad, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=quay.io/aaroc/code-rade-build-containers-build-slave-ubuntu1404}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='local'
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"devmapper: Thin Pool has 49350 free data blocks which is less than minimum required 163840 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:34)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:15)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:177)
	at com.nirima.jenkins.plugins.docker.DockerCloud.runContainer(DockerCloud.java:302)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:394)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:64)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:261)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:258)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

This seems like we've hit the limit imposed by lvm on the data containers. See https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/increase-capacity-on-a-running-device for some advice.

# steps : 

  1. [x] List the sizes of the devices.
  1. [x] Truncate data file to the size of the metadata file (approximately 200GB).
  1. [x] Verify the file size changed.
  1. [x] Reload data loop device
  1. [ ] Reload devicemapper thin pool.
     1. [x] Get the pool name first.
     1. [x] Dump the device mapper table first.
     1. [x] Calculate the real total sectors of the thin pool now.
Change the second number of the table info (i.e. the disk end sector) to reflect the new number of 512 byte sectors in the disk. For example, as the new loop size is 200GB, change the second number to 419430400.
     1. [x] Reload the thin pool with the new sector number

**Comment by brucellino** [comment]
busy reading the docker docs to understand what to do.

**Comment by brucellino** [comment]
Update : the device driver in use on the CI machine is : 

```
Storage Driver: devicemapper
 Pool Name: docker-253:3-10091-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 33.38 GB
 Data Space Total: 107.4 GB
 Data Space Available: 73.99 GB
 Metadata Space Used: 91.32 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.056 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
```

[The docs state :](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/increase-capacity-on-a-running-device#configure-docker-with-devicemapper)

> However, production deployments should not run under loop-lvm mode.

This seems like a bit dangerous to do (making physical volumes, etc), so I will re-size the loopback volume.

**Comment by brucellino** [comment]
Size of the devices : 

```
sudo  ls -lh /var/lib/docker/devicemapper/devicemapper/
total 32G
-rw-------. 1 root root 100G Jan 20 11:57 data
-rw-------. 1 root root 2.0G Jan 20 14:00 metadata
```

**Comment by brucellino** [comment]
New size of the data volume is 200 GB: 

```
 sudo ls -lh /var/lib/docker/devicemapper/devicemapper/
total 32G
-rw-------. 1 root root 200G Jan 20 15:06 data
-rw-------. 1 root root 2.0G Jan 20 14:00 metadata
```

This was truncated to be 25GB, as per the docs.

**Comment by brucellino** [comment]
Reloaded the data loop device  : 
```
sudo blockdev --getsize64 /dev/loop0
107374182400
```
then reload info : 

```
sudo losetup -c /dev/loop0
[ansible@ci ~]$ sudo blockdev --getsize64 /dev/loop0
214748364800
```

**Comment by brucellino** [comment]
Pool name : `docker-253:3-10091-pool`

Device mapper table : 
```
sudo dmsetup table docker-253:3-10091-pool
0 209715200 thin-pool 7:1 7:0 128 32768 1 skip_block_zeroing
```

the question now is - how do you : 
> Calculate the real total sectors of the thin pool now. 

Answer : divide the number of bits in the GB number  (214748364800 bits in a GB) by the size of the sector (512) : `214748364800/512 = 419430400`

**Comment by brucellino** [comment]
I've done the steps in the documentation, resized the volume to 200 GB. Let's see if the gcc jobs pass now.
