### ISSUE TITLE
NETCDF won't build

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE#13]
The jenkins config of NetCDF seems broken. Builds won't even start, getting a Java error:

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/SouthAfricaDigitalScience/netcdf-deploy
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
    at hudson.scm.SCM.checkout(SCM.java:484)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1259)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:622)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
    at hudson.model.Run.execute(Run.java:1759)
    at hudson.matrix.MatrixBuild.run(MatrixBuild.java:306)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
    at hudson.model.OneOffExecutor.run(OneOffExecutor.java:43)
Caused by: hudson.plugins.git.GitException: org.eclipse.jgit.api.errors.TransportException: https://github.com/SouthAfricaDigitalScience/netcdf-deploy: not authorized
    at org.jenkinsci.plugins.gitclient.JGitAPIImpl$2.execute(JGitAPIImpl.java:629)
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:761)
    ... 12 more
Caused by: org.eclipse.jgit.api.errors.TransportException: https://github.com/SouthAfricaDigitalScience/netcdf-deploy: not authorized
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
    at org.jenkinsci.plugins.gitclient.JGitAPIImpl$2.execute(JGitAPIImpl.java:627)
    ... 13 more
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/SouthAfricaDigitalScience/netcdf-deploy: not authorized
    at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:504)
    at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:309)
    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
    ... 14 more
ERROR: null
Finished: FAILURE
```

**Comment by brucellino** [comment]
The error is due to the fact that the repo has not yet been created on github.

**Comment by brucellino** [comment]
All done : 

```
ls /cvmfs/devrepo.sagrid.ac.za/generic/u1404/x86_64/netcdf/4.3.2-gcc-4.9.2/*
/cvmfs/devrepo.sagrid.ac.za/generic/u1404/x86_64/netcdf/4.3.2-gcc-4.9.2/bin:
nc-config  nccopy  ncdump  ncgen  ncgen3

/cvmfs/devrepo.sagrid.ac.za/generic/u1404/x86_64/netcdf/4.3.2-gcc-4.9.2/include:
netcdf.h  netcdf_par.h

/cvmfs/devrepo.sagrid.ac.za/generic/u1404/x86_64/netcdf/4.3.2-gcc-4.9.2/lib:
libnetcdf.a  libnetcdf.la  libnetcdf.so  libnetcdf.so.7  libnetcdf.so.7.2.0  pkgconfig

/cvmfs/devrepo.sagrid.ac.za/generic/u1404/x86_64/netcdf/4.3.2-gcc-4.9.2/share:
man
```
